name: GitHub Readme YouTube Cards and Blogs
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@dan.avila7,https://dev.to/feed/dani_avila7,https://danielsan.hashnode.dev/rss.xml"
      - name: Youtube
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCNabExUbWCar1WvCGWaPNdQ
